name: Build Lambda Layers

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-pyarrow:
    name: Build PyArrow Layer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build pyarrow
        run: |
          docker build -t pyarrow-layer --build-arg REQUIREMENTS=requirements.pyarrow.txt .
          id=$(docker create pyarrow-layer)
          docker cp $id:/layer.zip pyarrow-layer.zip
          docker rm $id
      - uses: actions/upload-artifact@v4
        with:
          name: pyarrow-layer
          path: pyarrow-layer.zip

  build-protobuf:
    name: Build Protobuf Layer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build protobuf
        run: |
          docker build -t protobuf-layer --build-arg REQUIREMENTS=requirements.protobuf.txt .
          id=$(docker create protobuf-layer)
          docker cp $id:/layer.zip protobuf-layer.zip
          docker rm $id
      - uses: actions/upload-artifact@v4
        with:
          name: protobuf-layer
          path: protobuf-layer.zip

  build-pandas:
    name: Build Pandas Layer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build pandas
        run: |
          docker build -t pandas-layer --build-arg REQUIREMENTS=requirements.pandas.txt .
          id=$(docker create pandas-layer)
          docker cp $id:/layer.zip pandas-layer.zip
          docker rm $id
      - uses: actions/upload-artifact@v4
        with:
          name: pandas-layer
          path: pandas-layer.zip

  build-common:
    name: Build Common Layer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build common
        run: |
          docker build -t common-layer --build-arg REQUIREMENTS=requirements.common.txt .
          id=$(docker create common-layer)
          docker cp $id:/layer.zip common-layer.zip
          docker rm $id
      - uses: actions/upload-artifact@v4
        with:
          name: common-layer
          path: common-layer.zip