name: Build Lambda Layers

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-pyarrow:
    name: Build PyArrow Layer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build pyarrow
        run: |
          docker build -t pyarrow-layer -f Dockerfile.pyarrow .
          id=$(docker create pyarrow-layer)
          docker cp $id:/pyarrow-layer.zip pyarrow-layer.zip
          docker rm $id
      - uses: actions/upload-artifact@v4
        with:
          name: pyarrow-layer
          path: pyarrow-layer.zip

  build-protobuf:
    name: Build Protobuf Layer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build protobuf
        run: |
          docker build -t protobuf-layer -f Dockerfile.protobuf .
          id=$(docker create protobuf-layer)
          docker cp $id:/protobuf-layer.zip protobuf-layer.zip
          docker rm $id
      - uses: actions/upload-artifact@v4
        with:
          name: protobuf-layer
          path: protobuf-layer.zip

  build-pandas:
    name: Build Pandas Layer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build pandas
        run: |
          docker build -t pandas-layer -f Dockerfile.pandas .
          id=$(docker create pandas-layer)
          docker cp $id:/pandas-layer.zip pandas-layer.zip
          docker rm $id
      - uses: actions/upload-artifact@v4
        with:
          name: pandas-layer
          path: pandas-layer.zip